USE Symphony;
insert into User (user_id, first_name, last_name, email, phone, city) values (4, 'Harald', 'Winpenny', 'hwinpenny3@apple.com', '561-518-5335', 'Velasco Ibarra');
insert into User (user_id, first_name, last_name, email, phone, city) values (5, 'Marla', 'Kimberley', 'mkimberley4@google.cn', '483-628-1123', 'Colosó');
insert into User (user_id, first_name, last_name, email, phone, city) values (6, 'Ofelia', 'Dahmke', 'odahmke5@livejournal.com', '772-166-0287', 'Xinchang');
insert into User (user_id, first_name, last_name, email, phone, city) values (7, 'Janel', 'McKyrrelly', 'jmckyrrelly6@nature.com', '476-382-4504', 'Al Ghizlānīyah');
insert into User (user_id, first_name, last_name, email, phone, city) values (8, 'Ferrel', 'Lamburn', 'flamburn7@dropbox.com', '522-897-7060', 'Petaling Jaya');
insert into User (user_id, first_name, last_name, email, phone, city) values (9, 'Nahum', 'Lorentzen', 'nlorentzen8@phoca.cz', '530-692-9612', 'Anjozorobe');
insert into User (user_id, first_name, last_name, email, phone, city) values (10, 'Joseito', 'Yonge', 'jyonge9@kickstarter.com', '207-777-9127', 'Radā‘');
insert into User (user_id, first_name, last_name, email, phone, city) values (11, 'Chloette', 'Everitt', 'ceveritta@hud.gov', '616-469-2616', 'Bridgetown');
insert into User (user_id, first_name, last_name, email, phone, city) values (12, 'George', 'Spencer', 'gspencerb@vkontakte.ru', '184-954-6234', 'Wawu');
insert into User (user_id, first_name, last_name, email, phone, city) values (13, 'Nicolea', 'Arnfield', 'narnfieldc@acquirethisname.com', '539-267-3480', 'Tisma');
insert into User (user_id, first_name, last_name, email, phone, city) values (14, 'Myrtle', 'Marklow', 'mmarklowd@pinterest.com', '824-658-4510', 'Daban');
insert into User (user_id, first_name, last_name, email, phone, city) values (15, 'Tobin', 'Downing', 'tdowninge@si.edu', '444-759-4864', 'Tanlad');
insert into User (user_id, first_name, last_name, email, phone, city) values (16, 'Barnebas', 'Mapston', 'bmapstonf@desdev.cn', '310-631-2092', 'Xiatuanpu');
insert into User (user_id, first_name, last_name, email, phone, city) values (17, 'Shanta', 'Boorn', 'sboorng@moonfruit.com', '884-754-1067', 'Pumwani');
insert into User (user_id, first_name, last_name, email, phone, city) values (18, 'Karlen', 'Mildner', 'kmildnerh@yahoo.co.jp', '359-205-1666', 'Valbo');
insert into User (user_id, first_name, last_name, email, phone, city) values (19, 'Sara-ann', 'Meedendorpe', 'smeedendorpei@amazon.de', '429-820-0484', 'Cimo de Vila');
insert into User (user_id, first_name, last_name, email, phone, city) values (20, 'Del', 'Damrell', 'ddamrellj@adobe.com', '554-448-9409', 'Vyškov');
insert into User (user_id, first_name, last_name, email, phone, city) values (21, 'Tymothy', 'Arghent', 'targhentk@printfriendly.com', '900-254-2019', 'Sosnovaya Polyana');
insert into User (user_id, first_name, last_name, email, phone, city) values (22, 'Teodoro', 'Soares', 'tsoaresl@bing.com', '188-780-7349', 'Tianxin');
insert into User (user_id, first_name, last_name, email, phone, city) values (23, 'Lloyd', 'Seiler', 'lseilerm@so-net.ne.jp', '574-728-5515', 'Piraju');
insert into User (user_id, first_name, last_name, email, phone, city) values (24, 'Kele', 'Van Niekerk', 'kvanniekerkn@slashdot.org', '330-889-3005', 'Warren');
insert into User (user_id, first_name, last_name, email, phone, city) values (25, 'Mable', 'Maymand', 'mmaymando@dailymotion.com', '389-768-3833', 'Itapaci');
insert into User (user_id, first_name, last_name, email, phone, city) values (26, 'Kippie', 'Reese', 'kreesep@a8.net', '190-390-1525', 'Ngori');
insert into User (user_id, first_name, last_name, email, phone, city) values (27, 'Addie', 'Castenda', 'acastendaq@mlb.com', '449-808-6368', 'Zhongzuiling');
insert into User (user_id, first_name, last_name, email, phone, city) values (28, 'Brody', 'Vockings', 'bvockingsr@dell.com', '264-315-0753', 'Disina');
insert into User (user_id, first_name, last_name, email, phone, city) values (29, 'Shena', 'Collick', 'scollicks@bloomberg.com', '217-496-3335', 'Phultala');
insert into User (user_id, first_name, last_name, email, phone, city) values (30, 'Malinde', 'Holbury', 'mholburyt@uol.com.br', '637-362-6103', 'Gengma');
insert into User (user_id, first_name, last_name, email, phone, city) values (31, 'Ardella', 'Cinnamond', 'acinnamondu@amazon.de', '716-539-5150', 'Yishan');
insert into User (user_id, first_name, last_name, email, phone, city) values (32, 'Yule', 'Bruggeman', 'ybruggemanv@techcrunch.com', '987-697-9999', 'Cibanten');
insert into User (user_id, first_name, last_name, email, phone, city) values (33, 'Elizabet', 'Broadley', 'ebroadleyw@google.ru', '761-825-1888', 'Mukun');
insert into User (user_id, first_name, last_name, email, phone, city) values (34, 'Judd', 'Suatt', 'jsuattx@mayoclinic.com', '359-663-8854', 'Garagoa');
insert into User (user_id, first_name, last_name, email, phone, city) values (35, 'Leonora', 'Seares', 'lsearesy@netscape.com', '428-604-1828', 'Tatsunochō-tominaga');
insert into User (user_id, first_name, last_name, email, phone, city) values (36, 'Waly', 'Belfield', 'wbelfieldz@desdev.cn', '749-937-8371', 'Shangxing');
insert into User (user_id, first_name, last_name, email, phone, city) values (37, 'Stefania', 'Roo', 'sroo10@prweb.com', '102-213-7629', 'Morocelí');
insert into User (user_id, first_name, last_name, email, phone, city) values (38, 'Gleda', 'Pykerman', 'gpykerman11@reverbnation.com', '215-989-4155', 'Waegwan');
insert into User (user_id, first_name, last_name, email, phone, city) values (39, 'Marcel', 'Mariault', 'mmariault12@senate.gov', '901-410-1060', 'Memphis');
insert into User (user_id, first_name, last_name, email, phone, city) values (40, 'Bertie', 'Andover', 'bandover13@nih.gov', '446-395-5490', 'Ronneby');
insert into User (user_id, first_name, last_name, email, phone, city) values (41, 'Preston', 'Springthorp', 'pspringthorp14@booking.com', '619-743-8251', 'Khotiv');
insert into User (user_id, first_name, last_name, email, phone, city) values (42, 'Georgia', 'Rapson', 'grapson15@wikispaces.com', '571-936-4138', 'Arlington');
insert into User (user_id, first_name, last_name, email, phone, city) values (43, 'Nadean', 'Grece', 'ngrece16@smugmug.com', '568-184-5417', 'Beijiang');
insert into User (user_id, first_name, last_name, email, phone, city) values (44, 'Wye', 'Heiner', 'wheiner17@bloglines.com', '785-144-2122', 'Dorowa Mining Lease');
insert into User (user_id, first_name, last_name, email, phone, city) values (45, 'Sonia', 'Cottisford', 'scottisford18@prlog.org', '218-546-8187', 'Mników');
insert into User (user_id, first_name, last_name, email, phone, city) values (46, 'Linell', 'Kellick', 'lkellick19@fastcompany.com', '688-397-8681', 'Untolovo');
insert into User (user_id, first_name, last_name, email, phone, city) values (47, 'Gavin', 'Revington', 'grevington1a@purevolume.com', '935-255-9209', 'Hekou');
insert into User (user_id, first_name, last_name, email, phone, city) values (48, 'Brier', 'Sommerled', 'bsommerled1b@comsenz.com', '612-709-7498', 'Almaznyy');
insert into User (user_id, first_name, last_name, email, phone, city) values (49, 'Daphna', 'Kennington', 'dkennington1c@wufoo.com', '885-974-6998', 'Tal’ne');
insert into User (user_id, first_name, last_name, email, phone, city) values (50, 'Dixie', 'Creak', 'dcreak1d@ft.com', '268-248-0368', 'Juàzeirinho');
insert into User (user_id, first_name, last_name, email, phone, city) values (51, 'Carmencita', 'Skitch', 'cskitch1e@sohu.com', '169-620-2528', 'Curuggoong');
insert into User (user_id, first_name, last_name, email, phone, city) values (52, 'Selina', 'Rohlfing', 'srohlfing1f@paypal.com', '211-257-7482', 'Salanegara');
insert into User (user_id, first_name, last_name, email, phone, city) values (53, 'Bordie', 'Wreakes', 'bwreakes1g@nih.gov', '870-664-2002', 'Kallithéa');
