USE Symphony;

insert into Artist (artist_id, first_name, last_name, email, phone, city) values (1, 'Selena', 'Legrand', 'slegrand0@upenn.edu', '283-877-7501', 'San Narciso');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (2, 'Ailyn', 'Gerriets', 'agerriets1@infoseek.co.jp', '283-902-8751', 'Albrechtice');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (3, 'Claudelle', 'Booth-Jarvis', 'cboothjarvis2@businessweek.com', '124-405-0225', 'Lingbei');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (4, 'Alleen', 'Thorndale', 'athorndale3@yelp.com', '100-171-4580', 'Zalaegerszeg');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (5, 'Ambrose', 'Sabatini', 'asabatini4@about.me', '919-926-1525', 'Betio Village');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (6, 'Rowney', 'Gallant', 'rgallant5@imageshack.us', '823-832-7084', 'Teresa');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (7, 'Gipsy', 'Jeanesson', 'gjeanesson6@mysql.com', '554-355-1859', 'Marquard');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (8, 'Trefor', 'Mannakee', 'tmannakee7@nhs.uk', '579-277-4548', 'Lendava');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (9, 'Theo', 'Gabbitus', 'tgabbitus8@mac.com', '561-889-8461', 'Caluquembe');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (10, 'Rhetta', 'Sallnow', 'rsallnow9@aboutads.info', '123-235-5179', 'Chengdong');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (11, 'Bev', 'Loverock', 'bloverocka@booking.com', '340-185-0698', 'Cervantes');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (12, 'Ernest', 'Buer', 'ebuerb@seattletimes.com', '845-642-1680', 'Tawali');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (13, 'Laurella', 'Sagg', 'lsaggc@un.org', '950-894-5274', 'Scholkine');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (14, 'Jolene', 'O''Coskerry', 'jocoskerryd@fc2.com', '142-209-6355', 'Groznyy');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (15, 'Torey', 'Hugnin', 'thugnine@aboutads.info', '924-286-3916', 'Aldana');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (16, 'Wilburt', 'Meace', 'wmeacef@yahoo.co.jp', '126-437-6979', 'Tortosendo');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (17, 'Wilie', 'Simounet', 'wsimounetg@com.com', '440-175-8011', 'Kaliterus');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (18, 'Kirsti', 'Byforth', 'kbyforthh@whitehouse.gov', '130-726-7197', 'Tall Tamr');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (19, 'Hannis', 'Skeel', 'hskeeli@bing.com', '801-256-8746', 'Jiangkou');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (20, 'Romeo', 'Pandie', 'rpandiej@archive.org', '704-818-8536', 'Chidian');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (21, 'Latisha', 'Cowpe', 'lcowpek@smh.com.au', '223-809-0529', 'Elói Mendes');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (22, 'Ninette', 'Bruno', 'nbrunol@washingtonpost.com', '195-381-5532', 'Zalantun');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (23, 'Lane', 'McMenamie', 'lmcmenamiem@skyrock.com', '964-826-2019', 'Barwałd Średni');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (24, 'Ambros', 'Faragher', 'afaraghern@wunderground.com', '775-118-2708', 'Boudinar');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (25, 'Jules', 'Exer', 'jexero@mail.ru', '877-479-6469', 'Ningzhong');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (26, 'Melanie', 'Pippin', 'mpippinp@xing.com', '179-805-6204', 'Skhira');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (27, 'Betty', 'Delamere', 'bdelamereq@tmall.com', '280-512-9877', 'Lebahseri');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (28, 'Tilly', 'McAlinden', 'tmcalindenr@tamu.edu', '542-348-0456', 'Ambato Boeny');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (29, 'Sandye', 'Whitear', 'swhitears@jigsy.com', '401-105-8487', 'Donggou');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (30, 'Alvie', 'Castells', 'acastellst@chron.com', '552-426-5890', 'Anahuac');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (31, 'Chev', 'Surmon', 'csurmonu@google.ca', '831-518-3366', 'Santa Cruz');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (32, 'Myrtia', 'Severn', 'msevernv@earthlink.net', '117-563-9020', 'Tāndo Mittha Khān');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (33, 'Margaretha', 'Kirkebye', 'mkirkebyew@ihg.com', '425-309-7615', 'Žlutice');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (34, 'Hillard', 'Bradnum', 'hbradnumx@meetup.com', '644-526-1561', 'Chaoyang');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (35, 'Danni', 'McKevin', 'dmckeviny@sfgate.com', '502-735-9393', 'Slovenska Bistrica');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (36, 'Glennis', 'Beebee', 'gbeebeez@redcross.org', '389-159-9779', 'Sviadnov');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (37, 'Vallie', 'Skone', 'vskone10@arstechnica.com', '738-552-0633', 'Vizal San Pablo');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (38, 'Fidelia', 'Starr', 'fstarr11@soup.io', '321-971-4281', 'Yanzhou');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (39, 'Jenn', 'Cattenach', 'jcattenach12@instagram.com', '690-450-8638', 'Kasungu');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (40, 'Deonne', 'Keveren', 'dkeveren13@comsenz.com', '898-540-0472', 'Youkounkoun');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (41, 'Winna', 'Pailin', 'wpailin14@home.pl', '697-334-4662', 'Porvoo');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (42, 'Cristie', 'Barbary', 'cbarbary15@ask.com', '387-660-0680', 'Osnabrück');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (43, 'Yank', 'Brecknell', 'ybrecknell16@smugmug.com', '468-436-5163', 'Socorro');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (44, 'Winona', 'Petchell', 'wpetchell17@mysql.com', '915-996-9000', 'Huangxi');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (45, 'Chico', 'Pawlick', 'cpawlick18@ask.com', '125-339-4657', 'Xinli');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (46, 'Ashlie', 'Ralestone', 'aralestone19@hugedomains.com', '323-790-9638', 'Burbank');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (47, 'Giacobo', 'Skune', 'gskune1a@eepurl.com', '453-526-8828', 'Wantan');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (48, 'Mitchel', 'Tisun', 'mtisun1b@livejournal.com', '381-427-5208', 'Kungshamn');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (49, 'Haydon', 'Purviss', 'hpurviss1c@scribd.com', '151-730-6010', 'Putrajaya');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (50, 'Luke', 'Vernazza', 'lvernazza1d@weebly.com', '514-711-0633', 'Santa Cecília');
