USE Symphony;
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '4', '4', '7');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Black Keys', '5', '5', '38');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Strokes', '6', '6', '31');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '7', '7', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '8', '8', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '9', '9', '41');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '10', '10', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '11', '11', '28');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blur', '12', '12', '34');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arctic Monkeys', '13', '13', '46');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '14', '14', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '15', '15', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Kings of Leon', '16', '16', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Lumineers', '17', '17', '23');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('My Chemical Romance', '18', '18', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The White Stripes', '19', '19', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '20', '20', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '21', '21', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '22', '22', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Killers', '23', '23', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Linkin Park', '24', '24', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '25', '25', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '26', '26', '29');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '27', '27', '40');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Fall Out Boy', '28', '28', '39');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blink-182', '29', '29', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Metallica', '30', '30', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '31', '31', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Muse', '32', '32', '4');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '33', '33', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '34', '34', '45');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pearl Jam', '35', '35', '30');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Florence + The Machine', '36', '36', '42');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Coldplay', '37', '37', '9');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '38', '38', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Radiohead', '39', '39', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '40', '40', '33');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '41', '41', '16');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Imagine Dragons', '42', '42', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '43', '43', '49');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Cure', '44', '44', '13');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blink-182', '45', '45', '37');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Red Hot Chili Peppers', '46', '46', '28');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Vampire Weekend', '47', '47', '8');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Oasis', '48', '48', '3');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pink Floyd', '49', '49', '38');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Metallica', '50', '50', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Killers', '1', '51', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Billie Eilish', '2', '52', '41');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '3', '53', '2');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arctic Monkeys', '4', '1', '46');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pink Floyd', '5', '2', '36');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '6', '3', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '7', '4', '7');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Black Keys', '8', '5', '38');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Strokes', '9', '6', '31');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '10', '7', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '11', '8', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '12', '9', '41');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '13', '10', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '14', '11', '28');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blur', '15', '12', '34');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arctic Monkeys', '16', '13', '46');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '17', '14', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '18', '15', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Kings of Leon', '19', '16', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Lumineers', '20', '17', '23');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('My Chemical Romance', '21', '18', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The White Stripes', '22', '19', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '23', '20', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '24', '21', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '25', '22', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Killers', '26', '23', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Linkin Park', '27', '24', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '28', '25', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '29', '26', '29');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '30', '27', '40');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Fall Out Boy', '31', '28', '39');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blink-182', '32', '29', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Metallica', '33', '30', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '34', '31', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Muse', '35', '32', '4');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '36', '33', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '37', '34', '45');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pearl Jam', '38', '35', '30');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Florence + The Machine', '39', '36', '42');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Coldplay', '40', '37', '9');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '41', '38', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Radiohead', '42', '39', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '43', '40', '33');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '44', '41', '16');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Imagine Dragons', '45', '42', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '46', '43', '49');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Cure', '47', '44', '13');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blink-182', '48', '45', '37');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Red Hot Chili Peppers', '49', '46', '28');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Vampire Weekend', '50', '47', '8');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Oasis', '1', '48', '3');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pink Floyd', '2', '49', '38');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Metallica', '3', '50', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Killers', '4', '51', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Billie Eilish', '5', '52', '41');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '6', '53', '2');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arctic Monkeys', '7', '1', '46');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pink Floyd', '8', '2', '36');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '9', '3', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '10', '4', '7');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Black Keys', '11', '5', '38');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Strokes', '12', '6', '31');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '13', '7', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '14', '8', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '15', '9', '41');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '16', '10', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '17', '11', '28');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blur', '18', '12', '34');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arctic Monkeys', '19', '13', '46');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '20', '14', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '21', '15', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Kings of Leon', '22', '16', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Lumineers', '23', '17', '23');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('My Chemical Romance', '24', '18', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The White Stripes', '25', '19', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '26', '20', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '27', '21', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '28', '22', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Killers', '29', '23', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Linkin Park', '30', '24', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '31', '25', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '32', '26', '29');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '33', '27', '40');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Fall Out Boy', '34', '28', '39');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blink-182', '35', '29', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Metallica', '36', '30', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '37', '31', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Muse', '38', '32', '4');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '39', '33', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '40', '34', '45');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pearl Jam', '41', '35', '30');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Florence + The Machine', '42', '36', '42');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Coldplay', '43', '37', '9');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '44', '38', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Radiohead', '45', '39', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '46', '40', '33');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '47', '41', '16');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Imagine Dragons', '48', '42', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '49', '43', '49');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Cure', '50', '44', '13');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blink-182', '1', '45', '37');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Red Hot Chili Peppers', '2', '46', '28');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Vampire Weekend', '3', '47', '8');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Oasis', '4', '48', '3');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pink Floyd', '5', '49', '38');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Metallica', '6', '50', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Killers', '7', '51', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Billie Eilish', '8', '52', '41');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '9', '53', '2');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arctic Monkeys', '10', '1', '46');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pink Floyd', '11', '2', '36');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '12', '3', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '13', '4', '7');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Black Keys', '14', '5', '38');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Strokes', '15', '6', '31');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '16', '7', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '17', '8', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '18', '9', '41');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '19', '10', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Panic! at the Disco', '20', '11', '28');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blur', '21', '12', '34');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arctic Monkeys', '22', '13', '46');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '23', '14', '25');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Arcade Fire', '24', '15', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Kings of Leon', '25', '16', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Lumineers', '26', '17', '23');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('My Chemical Romance', '27', '18', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The White Stripes', '28', '19', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '29', '20', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '30', '21', '32');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Clash', '31', '22', '1');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Killers', '32', '23', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Linkin Park', '33', '24', '14');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The War on Drugs', '34', '25', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '35', '26', '29');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '36', '27', '40');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Fall Out Boy', '37', '28', '39');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Blink-182', '38', '29', '10');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Metallica', '39', '30', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '40', '31', '19');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Muse', '41', '32', '4');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '42', '33', '44');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '43', '34', '45');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Pearl Jam', '44', '35', '30');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Florence + The Machine', '45', '36', '42');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Coldplay', '46', '37', '9');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Hozier', '47', '38', '15');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Radiohead', '48', '39', '17');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('AC/DC', '49', '40', '33');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Foo Fighters', '50', '41', '16');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Imagine Dragons', '1', '42', '47');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('Paramore', '2', '43', '49');
insert into Artist_Concert_Bridge (concert_name, artist_id, concert_id, venue_id) values ('The Cure', '3', '44', '13');
