USE Symphony;

<<<<<<< HEAD
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (4, 'Selena', 'Legrand', 'slegrand0@upenn.edu', '283-877-7501', 'San Narciso');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (5, 'Ailyn', 'Gerriets', 'agerriets1@infoseek.co.jp', '283-902-8751', 'Albrechtice');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (6, 'Claudelle', 'Booth-Jarvis', 'cboothjarvis2@businessweek.com', '124-405-0225', 'Lingbei');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (7, 'Alleen', 'Thorndale', 'athorndale3@yelp.com', '100-171-4580', 'Zalaegerszeg');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (8, 'Ambrose', 'Sabatini', 'asabatini4@about.me', '919-926-1525', 'Betio Village');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (9, 'Rowney', 'Gallant', 'rgallant5@imageshack.us', '823-832-7084', 'Teresa');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (10, 'Gipsy', 'Jeanesson', 'gjeanesson6@mysql.com', '554-355-1859', 'Marquard');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (11, 'Trefor', 'Mannakee', 'tmannakee7@nhs.uk', '579-277-4548', 'Lendava');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (12, 'Ernest', 'Buer', 'ebuerb@seattletimes.com', '845-642-1680', 'Tawali');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (13, 'Laurella', 'Sagg', 'lsaggc@un.org', '950-894-5274', 'Scholkine');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (14, 'Jolene', 'O''Coskerry', 'jocoskerryd@fc2.com', '142-209-6355', 'Groznyy');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (15, 'Torey', 'Hugnin', 'thugnine@aboutads.info', '924-286-3916', 'Aldana');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (16, 'Wilburt', 'Meace', 'wmeacef@yahoo.co.jp', '126-437-6979', 'Tortosendo');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (17, 'Wilie', 'Simounet', 'wsimounetg@com.com', '440-175-8011', 'Kaliterus');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (18, 'Kirsti', 'Byforth', 'kbyforthh@whitehouse.gov', '130-726-7197', 'Tall Tamr');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (19, 'Hannis', 'Skeel', 'hskeeli@bing.com', '801-256-8746', 'Jiangkou');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (20, 'Romeo', 'Pandie', 'rpandiej@archive.org', '704-818-8536', 'Chidian');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (21, 'Latisha', 'Cowpe', 'lcowpek@smh.com.au', '223-809-0529', 'Elói Mendes');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (22, 'Ninette', 'Bruno', 'nbrunol@washingtonpost.com', '195-381-5532', 'Zalantun');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (23, 'Lane', 'McMenamie', 'lmcmenamiem@skyrock.com', '964-826-2019', 'Barwałd Średni');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (24, 'Ambros', 'Faragher', 'afaraghern@wunderground.com', '775-118-2708', 'Boudinar');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (25, 'Jules', 'Exer', 'jexero@mail.ru', '877-479-6469', 'Ningzhong');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (26, 'Melanie', 'Pippin', 'mpippinp@xing.com', '179-805-6204', 'Skhira');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (27, 'Betty', 'Delamere', 'bdelamereq@tmall.com', '280-512-9877', 'Lebahseri');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (28, 'Tilly', 'McAlinden', 'tmcalindenr@tamu.edu', '542-348-0456', 'Ambato Boeny');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (29, 'Sandye', 'Whitear', 'swhitears@jigsy.com', '401-105-8487', 'Donggou');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (30, 'Alvie', 'Castells', 'acastellst@chron.com', '552-426-5890', 'Anahuac');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (31, 'Chev', 'Surmon', 'csurmonu@google.ca', '831-518-3366', 'Santa Cruz');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (32, 'Myrtia', 'Severn', 'msevernv@earthlink.net', '117-563-9020', 'Tāndo Mittha Khān');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (33, 'Margaretha', 'Kirkebye', 'mkirkebyew@ihg.com', '425-309-7615', 'Žlutice');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (34, 'Hillard', 'Bradnum', 'hbradnumx@meetup.com', '644-526-1561', 'Chaoyang');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (35, 'Danni', 'McKevin', 'dmckeviny@sfgate.com', '502-735-9393', 'Slovenska Bistrica');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (36, 'Glennis', 'Beebee', 'gbeebeez@redcross.org', '389-159-9779', 'Sviadnov');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (37, 'Vallie', 'Skone', 'vskone10@arstechnica.com', '738-552-0633', 'Vizal San Pablo');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (38, 'Fidelia', 'Starr', 'fstarr11@soup.io', '321-971-4281', 'Yanzhou');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (39, 'Jenn', 'Cattenach', 'jcattenach12@instagram.com', '690-450-8638', 'Kasungu');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (40, 'Deonne', 'Keveren', 'dkeveren13@comsenz.com', '898-540-0472', 'Youkounkoun');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (41, 'Winna', 'Pailin', 'wpailin14@home.pl', '697-334-4662', 'Porvoo');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (42, 'Cristie', 'Barbary', 'cbarbary15@ask.com', '387-660-0680', 'Osnabrück');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (43, 'Yank', 'Brecknell', 'ybrecknell16@smugmug.com', '468-436-5163', 'Socorro');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (44, 'Winona', 'Petchell', 'wpetchell17@mysql.com', '915-996-9000', 'Huangxi');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (45, 'Chico', 'Pawlick', 'cpawlick18@ask.com', '125-339-4657', 'Xinli');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (46, 'Ashlie', 'Ralestone', 'aralestone19@hugedomains.com', '323-790-9638', 'Burbank');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (47, 'Giacobo', 'Skune', 'gskune1a@eepurl.com', '453-526-8828', 'Wantan');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (48, 'Mitchel', 'Tisun', 'mtisun1b@livejournal.com', '381-427-5208', 'Kungshamn');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (49, 'Haydon', 'Purviss', 'hpurviss1c@scribd.com', '151-730-6010', 'Putrajaya');
insert into Artist (artist_id, first_name, last_name, email, phone, city) values (50, 'Luke', 'Vernazza', 'lvernazza1d@weebly.com', '514-711-0633', 'Santa Cecília');
=======
insert into Artist (first_name, last_name, email, phone, city) values ('Devonna', 'Scoyne', 'dscoyne0@boston.com', '340-793-5818', 'Reshetikha');
insert into Artist (first_name, last_name, email, phone, city) values ('Megen', 'Fulun', 'mfulun1@vk.com', '713-404-9686', 'Bunigeulis');
insert into Artist (first_name, last_name, email, phone, city) values ('Meris', 'Beddie', 'mbeddie2@stumbleupon.com', '926-685-8259', 'Khóra');
insert into Artist (first_name, last_name, email, phone, city) values ('Marisa', 'Goundrill', 'mgoundrill3@uol.com.br', '366-272-1440', 'Cerrito');
insert into Artist (first_name, last_name, email, phone, city) values ('Obadias', 'Frohock', 'ofrohock4@ted.com', '967-760-1460', 'Paris 13');
insert into Artist (first_name, last_name, email, phone, city) values ('Yettie', 'Crockford', 'ycrockford5@bbc.co.uk', '492-401-6984', 'Castelli');
insert into Artist (first_name, last_name, email, phone, city) values ('Shayne', 'Peakman', 'speakman6@patch.com', '144-785-5613', 'Prince Edward');
insert into Artist (first_name, last_name, email, phone, city) values ('Ewart', 'Skyrme', 'eskyrme7@marriott.com', '433-295-2959', 'Chacarita');
insert into Artist (first_name, last_name, email, phone, city) values ('Annabel', 'Nayshe', 'anayshe8@hexun.com', '834-400-2439', 'Ladoeiro');
insert into Artist (first_name, last_name, email, phone, city) values ('Joannes', 'Grzelczyk', 'jgrzelczyk9@gov.uk', '405-305-2719', 'Shiqiao');
insert into Artist (first_name, last_name, email, phone, city) values ('Sue', 'Sedwick', 'ssedwicka@answers.com', '320-873-3593', 'Caohe');
insert into Artist (first_name, last_name, email, phone, city) values ('Chlo', 'Kineton', 'ckinetonb@liveinternet.ru', '902-641-5758', 'Zlaté Hory');
insert into Artist (first_name, last_name, email, phone, city) values ('Kristel', 'Checkley', 'kcheckleyc@ask.com', '881-923-7936', 'Qinghua');
insert into Artist (first_name, last_name, email, phone, city) values ('Lorianna', 'Hallgalley', 'lhallgalleyd@hibu.com', '419-765-7420', 'Toledo');
insert into Artist (first_name, last_name, email, phone, city) values ('Cate', 'Wemyss', 'cwemysse@weibo.com', '482-551-7103', 'Dębowiec');
insert into Artist (first_name, last_name, email, phone, city) values ('Hammad', 'Tillett', 'htillettf@house.gov', '265-444-7608', 'Kořenov');
insert into Artist (first_name, last_name, email, phone, city) values ('Maria', 'Mault', 'mmaultg@csmonitor.com', '913-364-8906', 'Kansas City');
insert into Artist (first_name, last_name, email, phone, city) values ('Mathias', 'Oughton', 'moughtonh@pbs.org', '271-104-7262', 'Amsterdam Nieuw West');
insert into Artist (first_name, last_name, email, phone, city) values ('Layla', 'Dome', 'ldomei@wordpress.com', '146-547-6179', 'Bogorejo');
insert into Artist (first_name, last_name, email, phone, city) values ('Harris', 'Sallnow', 'hsallnowj@issuu.com', '492-573-3089', 'Atarodangwautu');
insert into Artist (first_name, last_name, email, phone, city) values ('Andrea', 'Kerwin', 'akerwink@wsj.com', '713-168-1573', 'Houston');
insert into Artist (first_name, last_name, email, phone, city) values ('Allayne', 'Shurville', 'ashurvillel@blog.com', '266-637-8908', 'Dingzhai');
insert into Artist (first_name, last_name, email, phone, city) values ('Efren', 'Gaynsford', 'egaynsfordm@hexun.com', '228-589-4173', 'Hlybokaye');
insert into Artist (first_name, last_name, email, phone, city) values ('Lonni', 'Gietz', 'lgietzn@mapquest.com', '316-825-9053', 'Wichita');
insert into Artist (first_name, last_name, email, phone, city) values ('Kale', 'Kierans', 'kkieranso@ucla.edu', '869-371-6034', 'Hallsberg');
insert into Artist (first_name, last_name, email, phone, city) values ('Noni', 'Keam', 'nkeamp@yahoo.co.jp', '184-827-1844', 'Kekeri');
insert into Artist (first_name, last_name, email, phone, city) values ('Ingmar', 'Fillary', 'ifillaryq@ft.com', '749-184-1352', 'Bayramaly');
insert into Artist (first_name, last_name, email, phone, city) values ('Allistir', 'Scrancher', 'ascrancherr@mtv.com', '836-201-1903', 'Rawuk');
insert into Artist (first_name, last_name, email, phone, city) values ('Thorny', 'Bradtke', 'tbradtkes@php.net', '252-172-7075', 'San Juan');
insert into Artist (first_name, last_name, email, phone, city) values ('Giuditta', 'Golborn', 'ggolbornt@ameblo.jp', '614-779-9580', 'Daduo');
insert into Artist (first_name, last_name, email, phone, city) values ('Genna', 'Gammade', 'ggammadeu@qq.com', '639-360-2025', 'Bacnar');
insert into Artist (first_name, last_name, email, phone, city) values ('Vasilis', 'Pollicott', 'vpollicottv@symantec.com', '589-429-1590', 'Borgholm');
insert into Artist (first_name, last_name, email, phone, city) values ('Shara', 'Juckes', 'sjuckesw@chron.com', '883-594-9955', 'Urasqui');
insert into Artist (first_name, last_name, email, phone, city) values ('Abrahan', 'Claiton', 'aclaitonx@cornell.edu', '767-142-3888', 'Cândido Mota');
insert into Artist (first_name, last_name, email, phone, city) values ('Tommi', 'Hayworth', 'thayworthy@washingtonpost.com', '148-157-9310', 'Kaytitinga');
insert into Artist (first_name, last_name, email, phone, city) values ('Belvia', 'Giametti', 'bgiamettiz@oaic.gov.au', '359-534-8601', 'Tongjiang');
insert into Artist (first_name, last_name, email, phone, city) values ('Jarrad', 'Horstead', 'jhorstead10@google.fr', '970-647-3670', 'Al Maḩallah al Kubrá');
insert into Artist (first_name, last_name, email, phone, city) values ('Norah', 'Wedderburn', 'nwedderburn11@ed.gov', '555-207-8562', 'Independencia');
insert into Artist (first_name, last_name, email, phone, city) values ('Iolande', 'Beddo', 'ibeddo12@bandcamp.com', '518-530-1884', 'Mananjary');
insert into Artist (first_name, last_name, email, phone, city) values ('Glendon', 'Leftridge', 'gleftridge13@google.com.br', '627-879-7343', 'Baicun');
insert into Artist (first_name, last_name, email, phone, city) values ('Jourdan', 'Girardy', 'jgirardy14@mapy.cz', '404-598-1342', 'Ozimek');
insert into Artist (first_name, last_name, email, phone, city) values ('Hamilton', 'Youthed', 'hyouthed15@cisco.com', '314-135-1774', 'Paraguarí');
insert into Artist (first_name, last_name, email, phone, city) values ('Ardenia', 'Herion', 'aherion16@amazon.de', '120-108-6854', 'Pantai');
insert into Artist (first_name, last_name, email, phone, city) values ('Bev', 'Neild', 'bneild17@yelp.com', '327-339-5726', 'Doushaguan');
insert into Artist (first_name, last_name, email, phone, city) values ('Lory', 'Dargavel', 'ldargavel18@vkontakte.ru', '268-469-3930', 'Cibulakan');
insert into Artist (first_name, last_name, email, phone, city) values ('Arther', 'Theurer', 'atheurer19@google.it', '251-480-2691', 'Hînceşti');
insert into Artist (first_name, last_name, email, phone, city) values ('Byran', 'Sewill', 'bsewill1a@shop-pro.jp', '693-714-8530', 'Lobanovo');
insert into Artist (first_name, last_name, email, phone, city) values ('Joaquin', 'Ping', 'jping1b@deliciousdays.com', '906-274-8543', 'Xinchengzi');
insert into Artist (first_name, last_name, email, phone, city) values ('Norina', 'Izakson', 'nizakson1c@google.co.jp', '283-376-9516', 'Daphu');
insert into Artist (first_name, last_name, email, phone, city) values ('Myrtle', 'Dafforne', 'mdafforne1d@topsy.com', '143-852-1414', 'Don Chedi');
>>>>>>> 61ce6a48cb262d06f1b72af89c83b29852c44235
