USE Symphony;
insert into Flags (description, user_id) values ('vel enim sit amet nunc viverra dapibus nulla suscipit ligula', '45');
insert into Flags (description, user_id) values ('quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc', '50');
insert into Flags (description, user_id) values ('massa id nisl venenatis lacinia aenean sit amet', '39');
insert into Flags (description, user_id) values ('quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', '29');
insert into Flags (description, user_id) values ('quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', '3');
insert into Flags (description, user_id) values ('quisque erat eros viverra eget congue', '43');
insert into Flags (description, user_id) values ('tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', '28');
insert into Flags (description, user_id) values ('at turpis donec posuere metus vitae', '25');
insert into Flags (description, user_id) values ('etiam pretium iaculis justo in hac habitasse platea dictumst etiam', '4');
insert into Flags (description, user_id) values ('magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', '23');
insert into Flags (description, user_id) values ('accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi', '42');
insert into Flags (description, user_id) values ('in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '5');
insert into Flags (description, user_id) values ('massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', '44');
insert into Flags (description, user_id) values ('augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', '16');
insert into Flags (description, user_id) values ('morbi a ipsum integer a nibh in quis justo maecenas', '2');
insert into Flags (description, user_id) values ('rhoncus aliquam lacus morbi quis tortor id', '41');
insert into Flags (description, user_id) values ('est donec odio justo sollicitudin ut suscipit a feugiat et eros', '48');
insert into Flags (description, user_id) values ('porttitor lorem id ligula suspendisse ornare consequat', '37');
insert into Flags (description, user_id) values ('in est risus auctor sed tristique in tempus sit amet sem', '11');
insert into Flags (description, user_id) values ('elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', '8');
insert into Flags (description, user_id) values ('condimentum neque sapien placerat ante nulla justo aliquam quis turpis', '24');
insert into Flags (description, user_id) values ('vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis', '27');
insert into Flags (description, user_id) values ('suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', '18');
insert into Flags (description, user_id) values ('duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a', '34');
insert into Flags (description, user_id) values ('mollis molestie lorem quisque ut erat', '22');
insert into Flags (description, user_id) values ('vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', '13');
insert into Flags (description, user_id) values ('nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat', '46');
insert into Flags (description, user_id) values ('libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in', '31');
insert into Flags (description, user_id) values ('ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', '20');
insert into Flags (description, user_id) values ('in eleifend quam a odio in hac habitasse platea dictumst maecenas ut', '15');
