USE Symphony;
insert into Genre_Artist (genre_id, artist_id, artist_name) values (1, '1', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (2, '2', 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (3, '3', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (4, '4', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (5, '5', 'The Black Keys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (6, '6', 'The Strokes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (7, '7', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (8, '8', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (9, '9', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (10, '10', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (11, '11', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (12, '12', 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (13, '13', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (14, '14', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (15, '15', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (16, '16', 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (17, '17', 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (18, '18', 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (19, '19', 'The White Stripes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (20, '20', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (21, '21', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (22, '22', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (23, '23', 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (24, '24', 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (25, '25', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (26, '26', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (27, '27', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (28, '28', 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (29, '29', 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (30, '30', 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (31, '31', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (32, '32', 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (33, '33', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (34, '34', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (35, '35', 'Pearl Jam');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (36, '36', 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (37, '37', 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (38, '38', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (39, '39', 'Radiohead');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (40, '40', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (41, '41', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (42, '42', 'Imagine Dragons');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (43, '43', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (44, '44', 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (45, '45', 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (46, '46', 'Red Hot Chili Peppers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (47, '47', 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (48, '48', 'Oasis');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (49, '49', 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (50, '50', 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (51, '51', 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (52, '52', 'Billie Eilish');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (53, '53', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (54, '1', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (55, '2', 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (56, '3', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (57, '4', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (58, '5', 'The Black Keys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (59, '6', 'The Strokes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (60, '7', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (61, '8', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (62, '9', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (63, '10', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (64, '11', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (65, '12', 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (66, '13', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (67, '14', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (68, '15', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (69, '16', 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (70, '17', 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (71, '18', 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (72, '19', 'The White Stripes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (73, '20', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (74, '21', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (75, '22', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (76, '23', 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (77, '24', 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (78, '25', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (79, '26', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (80, '27', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (81, '28', 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (82, '29', 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (83, '30', 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (84, '31', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (85, '32', 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (86, '33', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (87, '34', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (88, '35', 'Pearl Jam');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (89, '36', 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (90, '37', 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (91, '38', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (92, '39', 'Radiohead');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (93, '40', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (94, '41', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (95, '42', 'Imagine Dragons');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (96, '43', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (97, '44', 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (98, '45', 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (99, '46', 'Red Hot Chili Peppers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (100, '47', 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (101, '48', 'Oasis');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (102, '49', 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (103, '50', 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (104, '51', 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (105, '52', 'Billie Eilish');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (106, '53', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (107, '1', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (108, '2', 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (109, '3', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (110, '4', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (111, '5', 'The Black Keys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (112, '6', 'The Strokes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (113, '7', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (114, '8', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (115, '9', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (116, '10', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (117, '11', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (118, '12', 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (119, '13', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (120, '14', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (121, '15', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (122, '16', 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (123, '17', 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (124, '18', 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (125, '19', 'The White Stripes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (126, '20', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (127, '21', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (128, '22', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (129, '23', 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (130, '24', 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (131, '25', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (132, '26', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (133, '27', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (134, '28', 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (135, '29', 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (136, '30', 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (137, '31', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (138, '32', 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (139, '33', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (140, '34', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (141, '35', 'Pearl Jam');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (142, '36', 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (143, '37', 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (144, '38', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (145, '39', 'Radiohead');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (146, '40', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (147, '41', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (148, '42', 'Imagine Dragons');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (149, '43', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (150, '44', 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (151, '45', 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (152, '46', 'Red Hot Chili Peppers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (153, '47', 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (154, '48', 'Oasis');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (155, '49', 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (156, '50', 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (157, '51', 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (158, '52', 'Billie Eilish');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (159, '53', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (160, '1', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (161, '2', 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (162, '3', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (163, '4', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (164, '5', 'The Black Keys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (165, '6', 'The Strokes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (166, '7', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (167, '8', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (168, '9', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (169, '10', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (170, '11', 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (171, '12', 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (172, '13', 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (173, '14', 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (174, '15', 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (175, '16', 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (176, '17', 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (177, '18', 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (178, '19', 'The White Stripes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (179, '20', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (180, '21', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (181, '22', 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (182, '23', 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (183, '24', 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (184, '25', 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (185, '26', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (186, '27', 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (187, '28', 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (188, '29', 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (189, '30', 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (190, '31', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (191, '32', 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (192, '33', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (193, '34', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (194, '35', 'Pearl Jam');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (195, '36', 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (196, '37', 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (197, '38', 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (198, '39', 'Radiohead');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (199, '40', 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values (200, '41', 'Foo Fighters');
