USE Symphony;
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('48', 41, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('41', 28, 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('8', 16, 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('17', 11, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('22', 7, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('37', 21, 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('43', 18, 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('20', 37, 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('38', 53, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('25', 12, 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('19', 11, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('1', 7, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('50', 17, 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('16', 23, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('42', 17, 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('29', 4, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('32', 40, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('23', 48, 'Oasis');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('5', 4, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('47', 27, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('9', 23, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('18', 29, 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('39', 21, 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('6', 44, 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('2', 29, 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('31', 51, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('30', 46, 'Red Hot Chili Peppers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('12', 8, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('21', 30, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('34', 5, 'The Black Keys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('49', 15, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('33', 53, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('24', 29, 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('46', 32, 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('45', 13, 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('4', 42, 'Imagine Dragons');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('26', 36, 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('13', 23, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('35', 48, 'Oasis');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('40', 37, 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('11', 12, 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('36', 36, 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('15', 10, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('14', 36, 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('10', 34, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('7', 40, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('44', 53, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('27', 22, 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('28', 12, 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('3', 16, 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('9', 27, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('3', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('25', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('21', 19, 'The White Stripes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('31', 34, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('30', 22, 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('24', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('41', 44, 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('19', 41, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('45', 39, 'Radiohead');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('33', 7, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('32', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('46', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('40', 34, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('47', 39, 'Radiohead');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('13', 37, 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('15', 46, 'Red Hot Chili Peppers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('23', 32, 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('35', 5, 'The Black Keys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('48', 29, 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('2', 16, 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('17', 43, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('29', 26, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('50', 4, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('34', 49, 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('49', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('4', 24, 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('12', 53, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('42', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('28', 16, 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('37', 23, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('6', 36, 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('38', 8, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('1', 40, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('5', 8, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('14', 6, 'The Strokes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('43', 24, 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('36', 21, 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('11', 13, 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('44', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('16', 13, 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('22', 30, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('6', 4, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('7', 15, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('39', 18, 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('27', 12, 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('18', 30, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('8', 15, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('10', 7, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('20', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('9', 37, 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('36', 5, 'The Black Keys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('31', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('11', 23, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('4', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('23', 23, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('46', 24, 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('15', 8, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('28', 17, 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('50', 38, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('19', 24, 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('45', 15, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('3', 32, 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('1', 44, 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('34', 38, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('48', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('14', 17, 'The Lumineers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('49', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('2', 28, 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('42', 15, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('32', 37, 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('20', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('27', 51, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('10', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('5', 28, 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('40', 28, 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('30', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('29', 33, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('4', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('7', 8, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('9', 21, 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('18', 43, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('17', 53, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('8', 21, 'The Clash');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('22', 18, 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('43', 19, 'The White Stripes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('44', 10, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('12', 18, 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('6', 37, 'Coldplay');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('26', 28, 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('13', 41, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('33', 12, 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('24', 46, 'Red Hot Chili Peppers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('7', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('41', 12, 'Blur');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('6', 13, 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('21', 11, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('35', 15, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('38', 51, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('37', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('12', 24, 'Linkin Park');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('50', 35, 'Pearl Jam');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('35', 16, 'Kings of Leon');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('25', 41, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('43', 8, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('7', 48, 'Oasis');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('38', 23, 'The Killers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('13', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('44', 13, 'Arctic Monkeys');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('15', 18, 'My Chemical Romance');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('16', 38, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('3', 49, 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('8', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('27', 15, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('45', 34, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('4', 29, 'Blink-182');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('49', 40, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('34', 30, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('14', 4, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('39', 14, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('42', 27, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('28', 44, 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('5', 20, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('48', 32, 'Muse');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('46', 9, 'Arcade Fire');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('2', 6, 'The Strokes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('21', 41, 'Foo Fighters');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('47', 10, 'Panic! at the Disco');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('4', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('24', 49, 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('6', 19, 'The White Stripes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('9', 44, 'The Cure');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('29', 46, 'Red Hot Chili Peppers');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('11', 49, 'Pink Floyd');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('31', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('22', 34, 'AC/DC');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('36', 28, 'Fall Out Boy');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('33', 47, 'Vampire Weekend');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('23', 4, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('32', 6, 'The Strokes');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('37', 43, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('26', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('18', 25, 'The War on Drugs');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('17', 52, 'Billie Eilish');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('40', 20, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('41', 50, 'Metallica');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('18', 36, 'Florence + The Machine');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('20', 38, 'Hozier');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('19', 14, 'Paramore');
insert into Genre_Artist (genre_id, artist_id, artist_name) values ('1', 5, 'The Black Keys');
