USE Symphony;
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('27', null, 'Amalia', 'Ellam', 'aellam0@mediafire.com', '182-372-4711', 'Senior Quality Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('39', null, 'Florian', 'Dunk', 'fdunk1@baidu.com', '970-592-8027', 'Geological Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('48', null, 'Lesley', 'Higbin', 'lhigbin2@pcworld.com', '919-251-3475', 'Senior Editor');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('47', null, 'Carey', 'Bulloch', 'cbulloch3@umich.edu', '813-181-1666', 'Account Representative IV');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('14', null, 'Hugues', 'Grundy', 'hgrundy4@wired.com', '307-197-6457', 'Marketing Assistant');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('32', null, 'Lura', 'Yacob', 'lyacob5@dailymail.co.uk', '750-990-3621', 'Actuary');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('23', null, 'Gwennie', 'Cranmor', 'gcranmor6@gmpg.org', '648-130-6077', 'Executive Secretary');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('11', null, 'Nichol', 'Need', 'nneed7@blogtalkradio.com', '846-863-2057', 'Recruiting Manager');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('26', null, 'Marcello', 'Geale', 'mgeale8@nature.com', '526-393-4284', 'Technical Writer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('31', null, 'Antoni', 'Lamort', 'alamort9@smh.com.au', '632-645-7962', 'Chief Design Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('1', null, 'Kelwin', 'Rydeard', 'krydearda@reddit.com', '395-477-9018', 'Administrative Officer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('44', null, 'Rodrigo', 'Challis', 'rchallisb@psu.edu', '184-840-7685', 'Junior Executive');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('9', null, 'Carver', 'Witherdon', 'cwitherdonc@wired.com', '354-770-2297', 'Structural Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('46', null, 'Dore', 'Beet', 'dbeetd@phoca.cz', '664-590-1419', 'Assistant Media Planner');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('40', null, 'Janie', 'Yarr', 'jyarre@indiegogo.com', '327-104-6702', 'Geologist II');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('12', null, 'Donica', 'Tollett', 'dtollettf@php.net', '322-859-5748', 'Information Systems Manager');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('5', null, 'Ferd', 'Mc Curlye', 'fmccurlyeg@hubpages.com', '546-281-6345', 'Budget/Accounting Analyst III');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('35', null, 'Bernetta', 'Tunbridge', 'btunbridgeh@sina.com.cn', '964-163-8575', 'Civil Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('30', null, 'Shina', 'Abramowitch', 'sabramowitchi@techcrunch.com', '367-793-3881', 'GIS Technical Architect');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('20', null, 'Hermy', 'Chominski', 'hchominskij@photobucket.com', '795-757-4080', 'Community Outreach Specialist');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('22', null, 'Zachary', 'Wragge', 'zwraggek@telegraph.co.uk', '513-412-2670', 'Geological Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('6', null, 'Adham', 'McReynold', 'amcreynoldl@accuweather.com', '651-620-6705', 'Biostatistician IV');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('34', null, 'Marie-jeanne', 'Huygens', 'mhuygensm@woothemes.com', '885-668-6162', 'Assistant Manager');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('45', null, 'Hettie', 'Wartnaby', 'hwartnabyn@stanford.edu', '268-702-3721', 'Nurse');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values ('10', null, 'Sayers', 'Kaveney', 'skaveneyo@webs.com', '851-264-0861', 'Health Coach I');
