USE Symphony;
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Gratiana', 'Babinski', 'gbabinski0@github.com', '418-785-8023', 'Mechanical Systems Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Ingrid', 'Gergler', 'igergler1@wordpress.com', '804-964-9870', 'Chief Design Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Rosemonde', 'Ransome', 'rransome2@liveinternet.ru', '875-163-0317', 'Electrical Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Balduin', 'Brimson', 'bbrimson3@wikipedia.org', '535-942-7325', 'Environmental Specialist');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Heywood', 'Grigorushkin', 'hgrigorushkin4@google.ru', '852-944-4618', 'Civil Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Alma', 'Lauderdale', 'alauderdale5@trellian.com', '217-934-0075', 'Software Engineer IV');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Virgil', 'Trench', 'vtrench6@deviantart.com', '538-467-3745', 'Recruiting Manager');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Marice', 'Cherry', 'mcherry7@g.co', '830-296-8695', 'Account Representative II');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Denni', 'Challen', 'dchallen8@free.fr', '967-569-0534', 'Analog Circuit Design manager');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Tobie', 'Hogsden', 'thogsden9@meetup.com', '552-374-0775', 'Help Desk Operator');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Kimball', 'Matissoff', 'kmatissoffa@myspace.com', '501-121-1954', 'Chemical Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Ali', 'Gantzer', 'agantzerb@imdb.com', '152-514-2132', 'Desktop Support Technician');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Ermin', 'Poschel', 'eposchelc@umn.edu', '684-834-1260', 'VP Sales');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Bernardo', 'Wallworth', 'bwallworthd@nih.gov', '264-917-4149', 'Quality Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Edan', 'Sandyford', 'esandyforde@imdb.com', '951-507-3437', 'Project Manager');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Chevalier', 'Abbe', 'cabbef@forbes.com', '778-960-3631', 'Administrative Officer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Mirna', 'Huglin', 'mhugling@pinterest.com', '981-951-2316', 'General Manager');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Linet', 'Anchor', 'lanchorh@xing.com', '812-328-3540', 'Marketing Assistant');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Horatio', 'Croston', 'hcrostoni@google.cn', '300-310-9675', 'Food Chemist');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Chaim', 'Shieldon', 'cshieldonj@dion.ne.jp', '781-857-5417', 'Engineer III');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Eliot', 'Shrawley', 'eshrawleyk@cdc.gov', '386-411-9892', 'Human Resources Assistant IV');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Kari', 'Kuller', 'kkullerl@google.co.uk', '732-799-6855', 'Geologist I');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Eddy', 'Scopes', 'escopesm@redcross.org', '907-606-0167', 'Nuclear Power Engineer');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Agnella', 'Ready', 'areadyn@quantcast.com', '385-660-4811', 'Office Assistant II');
insert into Staff (venue_id, concert_id, first_name, last_name, email, phone, title) values (null, null, 'Merrill', 'Feasley', 'mfeasleyo@who.int', '210-691-5005', 'Software Engineer I');
